osx_image: xcode11.4
language: swift

script:
  - make test

before_deploy:
  - make release
  - zip -r catbird.zip catbird Catbird_CatbirdApp.bundle start.sh stop.sh LICENSE Public Sources/CatbirdAPI

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file: catbird.zip
  on:
    tags: true

after_deploy:
  - bundle exec pod trunk push Catbird.podspec
