osx_image: xcode10.2
language: swift
env:
  - SWIFT_VERSION=5.0
addons:
  homebrew:
    packages:
    - libressl
    update: true

script: 
  - make test

before_deploy:
  - make release 
  - zip -r catbird.zip catbird start.sh stop.sh LICENSE Public Resources Sources/CatbirdAPI

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file: catbird.zip
  on:
    tags: true

after_deploy:
  - bundle exec pod trunk push Catbird.podspec
