name: Release
on:
  release:
    types:
      - published
jobs:
  release:
    name: Publish release
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make release
      - name: Archive
        run: zip -r catbird.zip README.md LICENSE catbird
      - name: Upload GitHub Release Assets
        run: gh release upload ${{ github.event.release.tag_name }} catbird.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Cocoapods
        run: bundle install
      - name: Deploy to Cocoapods
        run: bundle exec pod trunk push Catbird.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
