
name: Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test Catbird package
        run: make test
        shell: bash
      - name: Build and test CatbirdApp package
        run: make test
        shell: bash
        working-directory: Packages/CatbirdApp
