
name: Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    container:
      image: swift:5.5.1-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        run: make test
  test-linux:
    name: Run tests on Linux
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        run: make test
