
name: Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        run: make test
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-20.04
    container:
      image: swift:5.5.1-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test catbird app
        run: swift test --package-path Packages/CatbirdApp --disable-automatic-resolution
